### ISSUE TITLE
compile fails on ac_list.c uncp

### ISSUE THREAD

**Issue by hsmalley** [phmarek/fsvs#16]
ac_list.c:79:31: error: ‘hlp_uncp’ undeclared here (not in a function)
 { .name=acl_##nam, .help_text=hlp_##nam, \
                               ^
ac_list.c:117:2: note: in expansion of macro ‘ACT’
  ACT(  uncp, cm__uncopy,         NULL),
  ^

**Comment by phmarek** [comment]
Fixed in 5f993f73b630686a54bdfcb5676c5e1a2fc76e52.
