### ISSUE TITLE
Typo in global.h causing compile to fail

### ISSUE THREAD

**Issue by hsmalley** [phmarek/fsvs#17]
Looks like line [849](https://github.com/phmarek/fsvs/blob/8d72d487f0a191bee8d50fdc2369d7ca3862ce20/src/global.h#L849) in global.h has a typo causing compiles to fail.

**Comment by phmarek** [comment]
Yes, thanks, fixed in 5f993f73b630686a54bdfcb5676c5e1a2fc76e52.

Started to cleanup some time ago, but it seems I got interrupted half-way before committing.
