### ISSUE TITLE
README does not mention needing to run ./configure nor how to generate configure

### ISSUE THREAD

**Issue by ryandesign** [phmarek/fsvs#21]
https://github.com/phmarek/fsvs/blob/a311665120b2e18a8b529a431ac8582892fa579c/README#L54-L59

Following just these instructions doesn't work because there is no Makefile yet:

```
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by phmarek** [comment]
85f57c04c9a9350e99835e9d3d2a2661a397ef11
