### ISSUE TITLE
Remove references to tigris.org

### ISSUE THREAD

**Issue by ryandesign** [phmarek/fsvs#26]
As you know, tigris.org ceased to exist in 2020 but multiple references to that domain remain in this codebase. For example, some of the manpages advise users to write to an email address at that domain for help, and the README provides an old link to the Subversion project at that domain. Please update all of these references to their current equivalents.

**Comment by phmarek** [comment]
Fixed in ce1a320519d345adbc33ca90d480410a6d8145cd
