### ISSUE TITLE
Provide a way to disable silent rules

### ISSUE THREAD

**Issue by ryandesign** [phmarek/fsvs#27]
Building fsvs hides the commands that were used to compile and link:

```
     CC checksum.c
     CC commit.c
     CC cp_mv.c
     CC direnum.c
     CC diff.c
     CC est_ops.c
     CC export.c
     CC fsvs.c
     CC hash_ops.c
     CC helper.c
     CC ignore.c
     CC info.c
     CC log.c
     CC options.c
     CC props.c
     CC racallback.c
     CC remote.c
     CC resolve.c
     CC revert.c
     CC status.c
     CC sync.c
     CC update.c
     CC url.c
     CC waa.c
     CC warnings.c
     Link fsvs
```

This makes it difficult to debug the build process and verify that all of the desired flags are passed at the right times. Please provide a way to disable silent rules. If you were using automake, it would do this automatically via a `--disable-silent-rules` configure argument, but since you aren't, you can implement it manually. Many projects allow this to be done via `make V=1` to enable verbose building.

**Comment by phmarek** [comment]
feb7013ff7acaf83b3fe9b7510b9a0df8aaa7b41
